### ISSUE TITLE
Illegal instruction error running HBB example

### ISSUE THREAD

**Issue by tli824** [oh-jinwoo94/gkm-align#1]
Hi there!

Really cool tool you developed here. I recently downloaded the git repo and am trying to install and run through the examples.

Running the HBB_LCR example you wrote in the README I get this error
`run_gkmalign.sh: line 9: 43737 Illegal instruction     ../../bin/gkm_align -t 1 HBB.to_align -d ../../data/genomes/ -g masker_models.txt -p 50 -o output_files -n
 HBB_LCR_mm10-hg38`

Was wondering whether you have any ideas why this is occurring. 

Thanks,
Tony

**Comment by oh-jinwoo94** [comment]
Hello Tony! Are you running in Linux OS environment? We haven't tested the package in non-Linux environments yet. Also please try using -p 1 to disable multithreading, which can be causing the problem. 

Best
Jin Woo

**Comment by tli824** [comment]
Thanks for the quick response Jin. I'm running CentOS Linux release 7.9.2009 (Core).

reducing to -p 1 did not solve the issue. I still get the same error.

**Comment by oh-jinwoo94** [comment]
Could you please send me the output of "uname -a"

**Comment by tli824** [comment]
`Linux hostname 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oh-jinwoo94** [comment]
Resolved by running gkm-align on AVX2 supporting  linux machine (lscpu | grep avx2).
