### ISSUE TITLE
Whole genome mapping between mouse and human

### ISSUE THREAD

**Issue by yuelaiwang** [oh-jinwoo94/gkm-align#3]
Hi!

I am running the tutorial in the README.md file. I wonder if you have a precomputed `.coord` file as `hg38-mm10_unweighted.coord` but is used for mapping mouse sequences to the human genome. Or, is it OK to flip the first two columns of `hg38-mm10_unweighted.coord` for this purpose? 

Also, near the end of the whole-genome mapping section, the `-q mm10` option in a demo command `../../bin/gkm_align  -t 2  human_brain_enhancers.bed  -c hg38-mm10_unweighted.coord -q mm10 -m -o output_files -n human_brain_enhancers_mapped_to_mm10` should be `-q hg38` for mapping human to mouse (querying human)?

**Comment by mbeer3** [comment]
Hi Eli--  I have a meeting with Jin-Woo later this week and we'll discuss this and get back to you.


Mike Beer
JHU BME & DGM

________________________________
From: Eli Wang ***@***.***>
Sent: Sunday, November 24, 2024 11:31 PM
To: oh-jinwoo94/gkm-align ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oh-jinwoo94/gkm-align] Whole genome mapping between mouse and human (Issue #3)


      External Email - Use Caution



Hi!

I am running the tutorial in the README.md file. I wonder if you have a precomputed .coord file as hg38-mm10_unweighted.coord but is used for mapping mouse sequences to the human genome. Or, is it OK to flip the first two columns of hg38-mm10_unweighted.coord for this purpose?

Also, near the end of the whole-genome mapping section, the -q mm10 option in a demo command ../../bin/gkm_align -t 2 human_brain_enhancers.bed -c hg38-mm10_unweighted.coord -q mm10 -m -o output_files -n human_brain_enhancers_mapped_to_mm10 should be -q hg38 for mapping human to mouse (querying human)?

**Comment by oh-jinwoo94** [comment]
Hi Eli sorry I missed your message, 

Using the same hg38-mm10_unweighted.coord,  you can map from mouse to human using `-q mm10` (querying mouse) and from human to mouse using `-q hg38` (querying human). 

Also, thank you so much for pointing out the mistake! You're right that it should be `-q hg38`. I fixed the README. 

Please let me know if you have any further question.

**Comment by yuelaiwang** [comment]
[heart]         Wang, Yuelai reacted to your message:
________________________________
