### ISSUE TITLE
questions about the chain file

### ISSUE THREAD

**Issue by 1221li** [oh-jinwoo94/gkm-align#4]
Hello, I would like to ask if how to make the file like "human_genomic_background_model_p_0.1.out" for other species?

**Comment by oh-jinwoo94** [comment]
Hi! I'll update the README to include an instruction on how to generate the background models. I will let you know when it's ready

**Comment by oh-jinwoo94** [comment]
@1221li 

Hi Xinmei, I added the following section to README:[ Generating gkm-SVM genome background models for repeat masking.](https://github.com/oh-jinwoo94/gkm-align?tab=readme-ov-file#generating-gkm-svm-genome-background-models-for-repeat-masking)

Please let me know if you have any further question!

**Comment by 1221li** [comment]
Hello,
I hope this email finds you well. I am in trouble again and would like to ask for your help
I am currently working with your scripts generate_syntenic_loci_to_align.sh and generate_genomic_background_model.sh, and I would greatly appreciate your clarification on a couple of points.

In the script generate_syntenic_loci_to_align.sh, there is a step for filtering using ENCODE syntenic intergenic loci, as shown below:

bash

filter using ENCODE syntenic intergenic loci
wget https://beerlab.org/gkmalign/Supplementary_Table_6.txt -O hg38_mm10_ortholog_syntenic_intergenic_pairs.txt
python ../../scripts/filter_short-seq-matches_by_syntenic_integenic_loci.py short_sequence_matches_2.axt hg38_mm10_ortholog_syntenic_pairs.txt > short_sequence_human-mouse_syntenic_intergenic.txt

I noticed that this filtering step specifically involves ENCODE data for human and mouse. However, as I am working with a non-model organism, it seems unlikely that relevant syntenic intergenic loci data would be available via ENCODE. In this scenario, would it be acceptable to skip this step, or is there an alternative approach you would recommend?

Regarding the module “Generating gkm-SVM genomic background models,” I carefully reviewed your script generate_genomic_background_model.sh but encountered a minor difficulty. My organism’s genome does not use the “chr” naming convention; for example, chromosome names use the “NC_” prefix, while some scaffolds are named with an "NW_" prefix due to the genome not being at a chromosome-level assembly yet. To accommodate this, I separated the script into individual steps and was able to complete the earlier parts.

However, in the following step:

bash

Step 5: Generate the final human genomic background model using the averaged kmer-weights
${gkmalign_path}/bin/train_masker nr11mers_genomic_model_hg38_L300_n${n}rAVG_weights_rho.out files/trainset_background_hg38-subset.txt ${genome_dir} ${threshold} human_genomic_background_model_p${threshold}.out
I couldn’t locate the file files/trainset_background_hg38-subset.txt in my working directory. Could you kindly advise at which step this file is generated? Alternatively, is this file optional when adapting the pipeline for non-model organisms?

Thank you very much for your time and invaluable feedback. I truly appreciate your support and guidance in helping me navigate these scripts for my project.

Looking forward to your response.

> [@1221li](https://github.com/1221li)
> 
> 嗨 Xinmei，我在 README 中添加了以下部分：[生成用于重复掩蔽的 gkm-SVM 基因组背景模型。](https://github.com/oh-jinwoo94/gkm-align?tab=readme-ov-file#generating-gkm-svm-genome-background-models-for-repeat-masking)
> 
> 如果您还有其他问题，请告诉我！
